# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.utilities_api import UtilitiesApi


class TestUtilitiesApi(unittest.TestCase):
    """UtilitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UtilitiesApi()

    def tearDown(self) -> None:
        pass

    def test_compute_nwm_bbox_nwm_compute_bbox_post(self) -> None:
        """Test case for compute_nwm_bbox_nwm_compute_bbox_post

        Compute Nwm Bbox
        """
        pass


if __name__ == '__main__':
    unittest.main()
