# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hydroshare_api import HydroshareApi


class TestHydroshareApi(unittest.TestCase):
    """HydroshareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HydroshareApi()

    def tearDown(self) -> None:
        pass

    def test_create_metadata_dataset_metadata_post(self) -> None:
        """Test case for create_metadata_dataset_metadata_post

        Create Metadata
        """
        pass

    def test_update_metadata_dataset_metadata_put(self) -> None:
        """Test case for update_metadata_dataset_metadata_put

        Update Metadata
        """
        pass


if __name__ == '__main__':
    unittest.main()
