# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.minio_api import MinioApi


class TestMinioApi(unittest.TestCase):
    """MinioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MinioApi()

    def tearDown(self) -> None:
        pass

    def test_generate_and_save_user_policy_policy_minio_cuahsi_get(self) -> None:
        """Test case for generate_and_save_user_policy_policy_minio_cuahsi_get

        Generate And Save User Policy
        """
        pass

    def test_generate_user_policy_policy_get(self) -> None:
        """Test case for generate_user_policy_policy_get

        Generate User Policy
        """
        pass

    def test_presigned_get_minio_presigned_get_workflow_id_get(self) -> None:
        """Test case for presigned_get_minio_presigned_get_workflow_id_get

        Presigned Get Minio
        """
        pass

    def test_presigned_get_url_url_workflow_id_get(self) -> None:
        """Test case for presigned_get_url_url_workflow_id_get

        Presigned Get Url
        """
        pass

    def test_presigned_put_minio_presigned_put_bucket_get(self) -> None:
        """Test case for presigned_put_minio_presigned_put_bucket_get

        Presigned Put Minio
        """
        pass

    def test_refresh_profile_profile_get(self) -> None:
        """Test case for refresh_profile_profile_get

        Refresh Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
