# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_oauth_oauth2_jwt_authorize_auth_cuahsi_authorize_get(self) -> None:
        """Test case for oauth_oauth2_jwt_authorize_auth_cuahsi_authorize_get

        Oauth:Oauth2.Jwt.Authorize
        """
        pass

    def test_oauth_oauth2_jwt_authorize_auth_front_authorize_get(self) -> None:
        """Test case for oauth_oauth2_jwt_authorize_auth_front_authorize_get

        Oauth:Oauth2.Jwt.Authorize
        """
        pass

    def test_oauth_oauth2_jwt_callback_auth_cuahsi_callback_get(self) -> None:
        """Test case for oauth_oauth2_jwt_callback_auth_cuahsi_callback_get

        Oauth:Oauth2.Jwt.Callback
        """
        pass

    def test_oauth_oauth2_jwt_callback_auth_front_callback_get(self) -> None:
        """Test case for oauth_oauth2_jwt_callback_auth_front_callback_get

        Oauth:Oauth2.Jwt.Callback
        """
        pass


if __name__ == '__main__':
    unittest.main()
