# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_submissions_response_model import UserSubmissionsResponseModel

class TestUserSubmissionsResponseModel(unittest.TestCase):
    """UserSubmissionsResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSubmissionsResponseModel:
        """Test UserSubmissionsResponseModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSubmissionsResponseModel`
        """
        model = UserSubmissionsResponseModel()
        if include_optional:
            return UserSubmissionsResponseModel(
                submissions = [
                    openapi_client.models.submission.Submission(
                        workflow_id = '', 
                        workflow_name = '', 
                        phase = 'Running', 
                        started_at = '', 
                        finished_at = '', 
                        estimated_duration = 56, )
                    ]
            )
        else:
            return UserSubmissionsResponseModel(
                submissions = [
                    openapi_client.models.submission.Submission(
                        workflow_id = '', 
                        workflow_name = '', 
                        phase = 'Running', 
                        started_at = '', 
                        finished_at = '', 
                        estimated_duration = 56, )
                    ],
        )
        """

    def testUserSubmissionsResponseModel(self):
        """Test UserSubmissionsResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
